spring.application.name=rms-v1

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://129.121.120.144:5432/rms_db?options=-c%20timezone=UTC
spring.datasource.username=postgres
spring.datasource.password=Neuro@123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8085

# MQTT Configuration (Compatible with EMQX)
mqtt.broker.url=tcp://129.121.120.144:1883
mqtt.client.id=rms-backend-prod
mqtt.username=admin
mqtt.password=Neurolinx@2026

# File Upload Configuration (for OTA binaries)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# OTA Server URL (The address the ESP32 will use to download the firmware)
ota.server.url=http://129.121.120.144:8085
